### ISSUE TITLE
shipment-picture-lambda-validator.jar: no such file or directory

### ISSUE THREAD

**Issue by justintrs** [tinyg210/shipment-list-demo#3]
Hello. I have followed every step perfectly . But at cmd: "tflocal apply" . I got this error:

`│ Error: opening S3 object source (../../shipment-picture-lambda-validator/target/shipment-picture-lambda-validator.jar): open ../../shipment-picture-lambda-validator/target/shipment-picture-lambda-validator.jar: no such file or directory
│ 
│   with aws_s3_object.lambda_code,
│   on main.tf line 59, in resource "aws_s3_object" "lambda_code":
│   59: resource "aws_s3_object" "lambda_code" {
│ 
`

I wonder where is shipment-picture-lambda-validator.jar file ? 
Thank you so much for this amazing demo.

**Comment by justintrs** [comment]
I fixed that by running **mvn package** inside _shipment-picture-lambda-validator_ folder

**Comment by tinyg210** [comment]
Hi Justin,
That's awesome that you figured it out. Please use `mvn clean package shade:shade`.This will create an uber-jar by packaging all the needed dependencies.
I just realized that I accidentally removed this part when updating the README file. Thanks for pointing that out! 🙌🏻

**Comment by justintrs** [comment]
> That's awesome that you figured it out. Please use `mvn clean`

Thank you. But now i stuck at **tflocal apply** for hours 😁

╷
│ Error: creating Lambda Function (shipment-picture-lambda-validator): waiting for completion: unexpected state 'Failed', wanted target 'Active'. last error: InternalError: Error while creating lambda: 
│ 
│   with aws_lambda_function.shipment_picture_lambda_validator,
│   on main.tf line 66, in resource "aws_lambda_function" "shipment_picture_lambda_validator":
│   66: resource "aws_lambda_function" "shipment_picture_lambda_validator" {
│ 
╵

Hope i can get some help ..

**Comment by tinyg210** [comment]
Did you try:
- restarting the container
- using the cleanup script in the /setup/terraform folder and making sure only the original files remain
- starting over with `tflocal init`, `tflocal plan -var 'env=dev'` and then `tflocal apply` ?
The reason I ask is that Terraform keeps track of resources in these generated files, so it knows what the current state is and what needs to be updated based on your changes. That means it will encounter issues creating new resources if there is a record of them existing.
If this is still failing, please check the logs of LocalStack for any other clues.

**Comment by justintrs** [comment]
> 
Thank you for your detailed reply. I have done everything you wrote above. Even I try on my other machine. It still has that error. (My LocalStack logs are fine, don't see any problems)

**Comment by justintrs** [comment]
I don't know why. But anybody who got the error like me above. Feel free to re-install Python on your machine (for me, it's Ubuntu). Then do the steps at README.md. Work perfectly! 
Thank Anca G for this awesome LocalStack demo.

**Comment by tinyg210** [comment]
Hi Justin,
I'm glad to hear it all worked out for you. 
Upon closer inspection of your console output, I realized this is coming from the new Lambda provider that we started using with LocalStack v2 (this demo was created using v1). Lambda functions are created and updated asynchronously in the new provider, like in AWS. Before invoking or adding any permissions to the function, it needs to transition from the state "Pending" to "Active". By default, Terraform will wait for the creation of the Lambda function to complete before moving on to the next resource (probably the permissions here). It polls the LocalStack API to check the status of the resource and waits until the function becomes available or reaches a stable state. This ensures that subsequent resource configurations, such as adding permissions, are applied to the function only after it is fully created. This is probably where things went wrong, and judging by the `unexpected state 'Failed'`, something happened before that failed the creation of the Lambda.
If the LocalStack debug logs (using the DEGUG=1 flag) don't help (of the main container), checking the Docker container logs of the Lambda function might give some clues (the Lambda spins up its own container). Your issue could have very well been caused by a Python version mismatch. 
I just got word that we just merged some improved error handling in Lambda, which should show better error messages in the LocalStack logs.
Thanks for being patient.
Anca
